# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'UiMenu.ui'
#
# Created by: PyQt5 UI code generator 5.15.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Menu(object):
    def setupUi(self, Menu):
        Menu.setObjectName("Menu")
        Menu.resize(900, 800)
        Menu.setMinimumSize(QtCore.QSize(900, 800))
        Menu.setMaximumSize(QtCore.QSize(1280, 800))
        Menu.setAutoFillBackground(False)
        self.centralwidget = QtWidgets.QWidget(Menu)
        self.centralwidget.setObjectName("centralwidget")
        self.layoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.layoutWidget.setGeometry(QtCore.QRect(70, 30, 761, 681))
        self.layoutWidget.setObjectName("layoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.layoutWidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.labelMenu = QtWidgets.QLabel(self.layoutWidget)
        font = QtGui.QFont()
        font.setPointSize(48)
        self.labelMenu.setFont(font)
        self.labelMenu.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.labelMenu.setAlignment(QtCore.Qt.AlignCenter)
        self.labelMenu.setObjectName("labelMenu")
        self.verticalLayout.addWidget(self.labelMenu)
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem)
        self.electronicButton = QtWidgets.QPushButton(self.layoutWidget)
        self.electronicButton.setMinimumSize(QtCore.QSize(300, 50))
        self.electronicButton.setMaximumSize(QtCore.QSize(300, 50))
        self.electronicButton.setObjectName("electronicButton")
        self.verticalLayout.addWidget(self.electronicButton, 0, QtCore.Qt.AlignHCenter)
        self.distanceButton = QtWidgets.QPushButton(self.layoutWidget)
        self.distanceButton.setMinimumSize(QtCore.QSize(300, 50))
        self.distanceButton.setMaximumSize(QtCore.QSize(300, 50))
        self.distanceButton.setObjectName("distanceButton")
        self.verticalLayout.addWidget(self.distanceButton, 0, QtCore.Qt.AlignHCenter)
        spacerItem1 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem1)
        Menu.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(Menu)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 900, 26))
        self.menubar.setObjectName("menubar")
        Menu.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(Menu)
        self.statusbar.setObjectName("statusbar")
        Menu.setStatusBar(self.statusbar)

        self.retranslateUi(Menu)
        QtCore.QMetaObject.connectSlotsByName(Menu)

    def retranslateUi(self, Menu):
        _translate = QtCore.QCoreApplication.translate
        Menu.setWindowTitle(_translate("Menu", "MainWindow"))
        self.labelMenu.setText(_translate("Menu", "Measurements GUI"))
        self.electronicButton.setText(_translate("Menu", "Electronic Measurements"))
        self.distanceButton.setText(_translate("Menu", "Force and Distance Measurements"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Menu = QtWidgets.QMainWindow()
    ui = Ui_Menu()
    ui.setupUi(Menu)
    Menu.show()
    sys.exit(app.exec_())
